### ISSUE TITLE
No velocity sensitivity in Drumrox-multi

### ISSUE THREAD

**Issue by BMuXBeats** [psemiletov/drumrox#13]
In comparison to Drumrox the velocity  sensitivity in Drumrox-multi doesn't work.
The "Ignore Velocity" checkbox i per default disabled and I didn't change it.

I've tested  the .LV2  Plugin V 3.2.1 from the ARCH repository in Ardour 8.4 and  Carla 2.5.8 as LV2 hosts.
In both cases the same result.

I work under LINUX Manjaro 23.1.4 (Vulcan) /KDE-Plasma V 5.27.11

**Comment by psemiletov** [comment]
All fixed, thank you!

**Comment by BMuXBeats** [comment]
Hi Peter,

thank you so much for this tool and fixing the bug instantly. 👏🏼  
It works flawless now. 💯👍🏻
