### ISSUE TITLE
Make use of Hydrogen mute groups

### ISSUE THREAD

**Issue by trebmuh** [psemiletov/drumrox#4]
Hi Peter.

Nice to see someone keeping this LV2 plugin up to date, thanks for that.

Can you tell me if your fork incorporate this ?
https://github.com/nicklan/drmr/issues/18

**Comment by psemiletov** [comment]
Hello!
Currently I'm trying to rewrite (at the local branch) all drumkit/sampler stuff of DrMr to C++ with a completely different code structure, so I'll keep in mind the mute groups. Thank you!

**Comment by trebmuh** [comment]
Nice to read!
I've quickly looked over at https://github.com/nicklan/drmr/issues and it seems there are a few others improvements suggestions.

By the way, I'm currently testing Drumrox for inclusion into LibraZiK.

**Comment by psemiletov** [comment]
I've done "mute groups"-kind functionality starting from the current commit. It works for hihat only and is turned on by default. Are we need an option to disable it at GUI?

**Comment by psemiletov** [comment]
Implemented at 2.2.0
