### ISSUE TITLE
Some answers

### ISSUE THREAD

**Issue by sjaehn** [psemiletov/drumrox#6]
... to your questions in the code:

https://github.com/psemiletov/drumrox/blob/0a40d55a8875de41718cb9998846f897f4b07295/drumrox.cpp#L323

3 bytes MIDI messages

https://github.com/psemiletov/drumrox/blob/0a40d55a8875de41718cb9998846f897f4b07295/drumrox.cpp#L464

The MIDI_NOTE_OFF byte is 0x8X with X is the channel number (0x0 to 0xF). And 0x8X shifted by 4 bytes is 8.

https://github.com/psemiletov/drumrox/blob/0a40d55a8875de41718cb9998846f897f4b07295/drumrox.cpp#L473

Same as above, but for MIDI_NOTE_ON which is 0x9X.

**Comment by psemiletov** [comment]
Thank you a lot!
